# Change these first
owner: Tet-Dev # Your GitHub username
repo: DazaiUptimeChecker # Your Github repository name

# Add your sites here
sites:
  - name: Dazai Site
    url: https://dazai.app
  - name: Dazai Discord Bot
    url: https://api.dazai.app:8080/uptime.html
    method: GET
    headers:
    - "Content-Type: application/json"
  - name: Dazai API
    url: https://api.dazai.app:8080/api/getPerms
    method: GET
    headers:
    - "Content-Type: application/json"
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /DazaiUptimeChecker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dazai Uptime
  introTitle: "A"
  introMessage: Dazai.app
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
